%%====================================================================
%%  💜 Purple Gradient
%%====================================================================
%%{ init: {
        "theme": "base",
        "themeVariables": {
            "background": "#0D1117",
            "lineColor": "#14B5FF",
            "textColor": "#fffff",
            "fontFamily": "'Aclonica', sans-serif",
            "borderRadius": "16",
        },
        "handDrawn": true,
    }  }%%
%%====================================================================
flowchart LR
    %%--------------------------------------------------------------
    classDef purple_grad0 fill:#301934,stroke:#5D3FD3,stroke-dasharray:6 6,color:#ffffff,rx:12,ry:12;
    classDef purple_grad1 fill:#45275a,stroke:#5D3FD3,stroke-dasharray:6 6,color:#ffffff,rx:12,ry:12;
    classDef purple_grad2 fill:#45275a,stroke:#5D3FD3,stroke-dasharray:6 6,color:#ffffff,rx:12,ry:12;
    classDef purple_grad3 fill:#5c3b80,stroke:#5D3FD3,stroke-dasharray:6 6,color:#ffffff,rx:12,ry:12;
    classDef purple_grad4 fill:#7495b5,stroke:#5D3FD3,stroke-width:2px,color:#ffffff,rx:12,ry:12;
    classDef purple_grad5 fill:#8ac9d9,stroke:#5D3FD3,stroke-width:2px,color:#ffffff,rx:12,ry:12;
    classDef purple_grad6 fill:#a0f0ff,stroke:#5D3FD3,stroke-width:2px,color:#ffffff,rx:12,ry:12;

    %%--------------------------------------------------------------
    %% CORE PIPELINE
    %%--------------------------------------------------------------
    subgraph purple_0["0️⃣ purple_grad0"]
    direction LR
        subgraph purple_1A["1️⃣ purple_grad1"]
        direction LR
            subgraph purple_2A["2️⃣ purple_grad2"]
            direction LR
                subgraph purple_3AA["3️⃣ purple_grad3"]
                direction TB
                    purple_4AB["4️⃣ purple_grad4"] --> purple_5A["5️⃣ purple_grad5"] --> purple_6A["6️⃣ purple_grad6"]
                    purple_4AB --> purple_5B["5️⃣ purple_grad5"] --> purple_6B["6️⃣ purple_grad6"]
                    purple_5B --> purple_6C["6️⃣ purple_grad6"]
                    purple_5C --> purple_6B
                    purple_4C["4️⃣ purple_grad4"] --> purple_5C["5️⃣purple_grad5"] --> purple_6C
                end
            end
        end


    end

    purple_0:::purple_grad0
    purple_1A:::purple_grad1
    purple_2A:::purple_grad2
    purple_3AA:::purple_grad3
    purple_4AB:::purple_grad4
    purple_4C:::purple_grad4
    purple_5A:::purple_grad5
    purple_5B:::purple_grad5
    purple_5C:::purple_grad5
    purple_6A:::purple_grad6
    purple_6B:::purple_grad6
    purple_6C:::purple_grad6







