# cli_train.py
"""
Command-line training runner for Project 2 (``lf-pinn-inverse-schrodinger`).

The purpose of this script is to provide a reproducible command-line interface around the canonical training primmitives in ``src/train.py``. It builds on the synthetic inverse Schrödinger problem, trains the model, logs losses to SQLite, and writes run artifacts for later analysis or dashboard applications.

Generated run artifacts include:
- ``config.json``: training configuration and hyperparameters
- ``history.json``: per-epoch loss history
- ``diagnostics.npz``: learned energies, potential, wavefunctions, and POD data
- ``ground_truth.npz``: analytic reference quantities for comparison
- ``model.pt``: trained model state directory
- ``run_id.txt``: unique identifier for the run

Usage examples
--------------
Run with default settings from the project root:

    python -m cli.cli_train

Run with explicit loss weights:

    python -m cli.cli_trian \\
        --lambda-data 1.5 \\
        --lambda-physics 0.5 \\
        --lambda-smooth 0.25 \\
        --lambda-ordered 1.0

Provenance: Initial implementation generated by an LLM and not yet fully reviewed by a human maintainer.
Maintainer: Eigenscribe / Scriber Labs
Date: 02-2026
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add project root and src to sys.path to allow imports when running as a script
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.append(str(PROJECT_ROOT / "src"))

from typing import Final, List, Tuple

import numpy as np
import torch
from torch import Tensor

torch.set_default_dtype(torch.float64)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts" / "runs"

# ----------------------------------------------------------------------
# 1️⃣ Import the core training utilities from src/train.py
# ----------------------------------------------------------------------
from db_logger import RunLogger
from train import (
    train_step,
    set_global_seed,
    make_grid,
    InverseSchrodingerModel,
)
from pod import physical_pod_decomposition
from utils import l2_inner_product
from visualizations import (
    plot_loss_history,
    plot_potential,
    plot_wavefunctions,
    plot_energy_spectrum,
    plot_density_vs_observed,
    plot_pod_singular_values,
    plot_pod_first_three_spatial_modes,
    plot_overlap_heatmap,
    plot_pod_temporal_modes,
    plot_pod_temporal_overlap_heatmap,
    plot_pod_temporal_cross_overlap_heatmap,
    plot_pod_eigen_alignment,
)

# ----------------------------------------------------------------------
# 2️⃣ Argument parser for CLI
# ----------------------------------------------------------------------
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m cli.cli_train",
        description="Train a low-fidelity PINN for the inverse Schrödinger problem.",
    )
    parser.add_argument("--n_modes", type=int, default=3,
                        help="Number of eigenmodes and associated energy eigenvalues to learn")
    parser.add_argument("--hidden", type=int, default=64,
                        help="Number of neurons per hidden layer")
    parser.add_argument("--epochs", type=int, default=6_000,
                        help="Number of training epochs")
    parser.add_argument("--lr", type=float, default=5e-3,
                        help="Learning rate")
    parser.add_argument("--n_points", type=int, default=256,
                        help="Number of spatial collocation points (i.e., grid resolution)")
    parser.add_argument("--seed", type=int, default=27,
                        help="Random seed")
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="cpu | cuda | cuda:0 | ...",
    )
    parser.add_argument("--log_every", type=int, default=800,
                        help="Print interval every x epochs")
    parser.add_argument(
        "--log-db",
        type=str,
        default=str(DATA_DIR / "training_runs.db"),
        help="Path to the SQLite training database",
    )

    # Loss weights
    parser.add_argument("--lambda-data", type=float, default=1.5,
                        help="Weight for the data-fit loss (rho and energy)")
    parser.add_argument("--lambda-physics", type=float, default=0.5,
                        help="Weight for the TISE physics loss")
    parser.add_argument("--lambda-smooth", type=float, default=0.25,
                        help="Weight for the potential smoothness regularization")
    parser.add_argument("--lambda-ordered", type=float, default=1.0,
                        help="Weight for the energy ordering constraint")

    return parser.parse_args(argv)

# ----------------------------------------------------------------------
# 3️⃣ Helper to build the model & synthetic data
# ----------------------------------------------------------------------
def _build_problem(args: argparse.Namespace) -> Tuple[
    InverseSchrodingerModel,
    torch.optim.Optimizer,
    Tensor,
    float,
    List[Tensor],
    Tensor,
    dict[str, float],
    List[Tensor],
    Tensor,
    Tensor,
]:
    """
    Build the model and synthetic data for the quantum harmonic oscillator.

    Parameters
    ----------
    args : argparse.Namespace
        Command-line arguments containing model and training configuration.

    Returns
    -------
    Tuple[...]
        A tuple containing:
        - model: The InverseSchrodingerModel instance.
        - optimizer: The Adam optimizer.
        - x: Spatial grid tensor.
        - dx: Grid spacing.
        - rho_obs: Observed densities.
        - E_obs: Observed energies.
        - lambdas: Loss weighting factors.
        - psi_true: Ground truth wavefunctions.
        - E_true: Ground truth energies.
        - V_true: Ground truth potential.
    """
    device: Final = torch.device(args.device)

    # Spatial grid
    x = make_grid(-5.0, 5.0, args.n_points, device=device)
    dx = float(x[1] - x[0])

    # Analytic eigenfunctions (Hermite-Gaussians) for the chosen analytic potential (harmonic oscillator)
    def hermite_gauss(n: int, x_vals: torch.Tensor) -> torch.Tensor:
        """Return the nth normalized harmonic oscillator eigenfunction."""
        from math import factorial, sqrt, pi
        import scipy.special as sp
        norm = 1.0 / sqrt(2.0 ** n * factorial(n)) * (pi ** -0.25)
        # sp.hermite returns a callable polynomial; evaluate on x_vals
        return norm * sp.hermite(n)(x_vals) * torch.exp(-0.5 * x_vals ** 2)

    # Synthetic observations (replace these with real data as you see fit)
    psi_true = [hermite_gauss(n, x.squeeze()) for n in range(args.n_modes)]
    E_true = torch.arange(args.n_modes,
                          dtype=torch.float64) + 0.5  # exact energies for the quantum harmonic oscillator (hbar = omega = 1)
    V_true = 0.5 * x.squeeze() ** 2

    rho_obs = [psi ** 2 + 0.02 * torch.randn_like(psi) for psi in psi_true]
    E_obs = E_true + 0.05 * torch.randn_like(E_true)

    # Loss weights (from CLI arguments)
    lambdas = {
        "data": args.lambda_data,
        "physics": args.lambda_physics,
        "smooth": args.lambda_smooth,
        "ordered": args.lambda_ordered,
    }

    # Model
    model = InverseSchrodingerModel(
        n_states=args.n_modes,
        hidden_dims=[args.hidden, args.hidden],
        device=device,
        dx=dx,
    ).to(device)

    # Optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    return model, optimizer, x, dx, rho_obs, E_obs, lambdas, psi_true, E_true, V_true

# ------------------------------------------------------------------------------
# 3️⃣ Entry-point
# ------------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> None:    # noqa: D401
    """
    Entry point for ``python -m cli_train``.
    """
    args = parse_args(argv)

    # Seed everything for reproducibility
    set_global_seed(args.seed, deterministic=True)

    device: Final = torch.device(args.device)
    print(f"🖥️  Using device: {device}")

    # Build model, optimizer, data, etc.
    model, optimizer, x, dx, rho_obs, E_obs, lambdas, psi_true, E_true, V_true = _build_problem(args)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    db_path = Path(args.log_db)
    if not db_path.is_absolute():
        db_path = PROJECT_ROOT / db_path

    hyperparams = {
        "n_modes": args.n_modes,
        "hidden": args.hidden,
        "epochs": args.epochs,
        "lr": args.lr,
        "n_points": args.n_points,
        "seed": args.seed,
        "device": args.device,
        "log_every": args.log_every,
        "lambdas": lambdas,
        "dx": dx,
    }

    print(f"dx: {dx}")
    print(f"x dtype: {x.dtype}")
    print(f"E_obs dtype: {E_obs.dtype}")
    print(f"rho_obs[0] dtype: {rho_obs[0].dtype}")
    print(f"model param dtype: {next(model.parameters()).dtype}")

    with RunLogger(db_path) as logger:
        run_id = logger.start_run(hyperparams=hyperparams, seed=args.seed)
        run_artifacts_dir = ARTIFACTS_DIR / run_id
        run_artifacts_dir.mkdir(parents=True, exist_ok=True)

        # ------------------------------------------------------------------
        # Training loop (simple version – prints every `log_every` steps)
        # ------------------------------------------------------------------
        history: list[dict[str, float]] = []

        for epoch in range(1, args.epochs + 1):
            optimizer.zero_grad()
            total_loss, loss_physics, loss_data, loss_smooth, loss_ordered = train_step(model, x, dx, rho_obs, E_obs, lambdas)
            total_loss.backward()
            optimizer.step()

            # Detach and convert to float for history
            losses_dict = {
                "epoch": epoch,
                "total_loss": float(total_loss.detach()),
                "physics_loss": float(loss_physics.detach()),
                "data_loss": float(loss_data.detach()),
                "smooth_loss": float(loss_smooth.detach()),
                "ordered_loss": float(loss_ordered.detach()),
            }
            history.append(losses_dict)

            logger.log_metric(
                run_id=run_id,
                epoch=epoch,
                losses_dict={
                    "total_loss": total_loss.detach(),
                    "physics_loss": loss_physics.detach(),
                    "data_loss": loss_data.detach(),
                    "smooth_loss": loss_smooth.detach(),
                    "ordered_loss": loss_ordered.detach(),
                },
            )

            if epoch % args.log_every == 0 or epoch == args.epochs:
                print(f"[{epoch:>5}/{args.epochs}] loss = {total_loss.item():.6e}")

        # ----------------------------------------------------------------------
        # 🎁 Save Ground Truth
        # ----------------------------------------------------------------------
        torch.save({
            "x": x.cpu(),
            "V_true": V_true.cpu(),
            "psi_true": [p.cpu() for p in psi_true],
            "E_true": E_true.cpu(),
        }, run_artifacts_dir / "ground_truth.pt")

        # ----------------------------------------------------------------------
        # 3️⃣ Compute Final Diagnostics
        # ----------------------------------------------------------------------
        model.eval()
        with torch.no_grad():
            V_learned = model.V_theta(x).squeeze()
            psi_learned = model.psi_theta(x, dx)
            E_learned = model.E_theta()

            # ------------------------------------------------------------------
            # ✨ Sort and Perform POD
            # ------------------------------------------------------------------
            # Sort learned quantities for diagnostic/reporting artifacts only.
            # Training itself uses the raw energy ordering so the ordering loss remains a soft penalty.
            idx = torch.argsort(E_learned)
            E_learned = E_learned[idx]
            psi_learned = [psi_learned[i] for i in idx]

            # POD Analysis using the same trapezoidal physical POD pipeline as the notebook.
            # Stack wavefunctions as columns: (n_points, n_modes)
            psi_matrix = torch.stack(psi_learned, dim=1)
            pod_modes_physical, S, Vh, pod_modes_euclidean = physical_pod_decomposition(
                psi_matrix,
                dx,
                reference_modes=psi_matrix,
                align_signs=True,
            )

            # Overlap Matrix (learned vs learned)
            n_modes = len(psi_learned)
            overlap_learned = torch.zeros(
                (n_modes, n_modes),
                device=device,
                dtype=psi_matrix.dtype,
            )
            for i in range(n_modes):
                for j in range(n_modes):
                    overlap_learned[i, j] = l2_inner_product(
                        psi_learned[i],
                        psi_learned[j],
                        dx,
                    )

            # Overlap Matrix (learned vs true)
            overlap_true = torch.zeros(
                (n_modes, n_modes),
                device=device,
                dtype=psi_matrix.dtype,
            )
            for i in range(n_modes):
                for j in range(n_modes):
                    overlap_true[i, j] = l2_inner_product(
                        psi_learned[i],
                        psi_true[j].to(device),
                        dx,
                    )

        # ----------------------------------------------------------------------
        # 4️⃣ Save Plots
        # ----------------------------------------------------------------------
        lambdas = {
            "data": args.lambda_data,
            "physics": args.lambda_physics,
            "smooth": args.lambda_smooth,
            "ordered": args.lambda_ordered,
        }

        plot_loss_history(
            epochs=[h["epoch"] for h in history],
            total=[h["total_loss"] for h in history],
            physics=[h["physics_loss"] for h in history],
            data=[h["data_loss"] for h in history],
            smooth=[h["smooth_loss"] for h in history],
            ordered=[h["ordered_loss"] for h in history],
            lambdas=lambdas,
            out_path=run_artifacts_dir / "loss_history.png",
        )

        plot_potential(
            x=x,
            V_true=V_true,
            V_learned=V_learned,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "potential.png",
        )

        plot_wavefunctions(
            x=x,
            psi_true=psi_true,
            psi_learned=psi_learned,
            out_path=run_artifacts_dir / "wavefunctions.png",
        )

        plot_energy_spectrum(
            E_true=E_true,
            E_learned=E_learned,
            out_path=run_artifacts_dir / "energy_spectrum.png",
        )

        plot_pod_singular_values(
            singular_values=S,
            out_path=run_artifacts_dir / "pod_singular_values.png",
        )

        plot_pod_first_three_spatial_modes(
            x=x,
            spatial_modes=pod_modes_physical,
            ground_truth=psi_true,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "pod_spatial_modes.png",
        )

        plot_overlap_heatmap(
            psi_theta=psi_learned,
            dx=dx,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "overlap_heatmap.png",
        )

        plot_pod_temporal_modes(
            Vh=Vh,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "pod_temporal_modes.png",
        )

        plot_pod_temporal_overlap_heatmap(
            Vh=Vh,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "pod_temporal_overlap.png",
        )

        plot_pod_temporal_cross_overlap_heatmap(
            Vh=Vh,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "pod_temporal_cross_overlap.png",
        )

        plot_pod_eigen_alignment(
            pod_modes_physical=pod_modes_physical,
            psi_true_matrix=torch.stack(psi_true, dim=1),
            dx=dx,
            lambdas=lambdas,
            out_path=run_artifacts_dir / "pod_eigen_alignment.png",
        )

        # ----------------------------------------------------------------------
        # 5️⃣ Save diagnostics metadata
        # ----------------------------------------------------------------------
        # Prepare diagnostics dictionary for saving
        diagnostics = {
            "E_learned": E_learned.cpu().numpy(),
            "V_learned": V_learned.cpu().numpy(),
            "psi_learned": torch.stack(psi_learned).cpu().numpy(),
            "pod_singular_values": S.cpu().numpy(),
            "pod_modes_physical": pod_modes_physical.cpu().numpy(),
            "pod_modes_euclidean": pod_modes_euclidean.cpu().numpy(),
            "pod_vh": Vh.cpu().numpy(),
            "overlap_learned": overlap_learned.cpu().numpy(),
            "overlap_true": overlap_true.cpu().numpy(),
        }

        np.savez(run_artifacts_dir / "diagnostics.npz", **diagnostics)

        torch.save(model.state_dict(), run_artifacts_dir / "model.pt")
        (run_artifacts_dir / "config.json").write_text(
            json.dumps(hyperparams, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        (run_artifacts_dir / "history.json").write_text(
            json.dumps(history, indent=2),
            encoding="utf-8",
        )
        (run_artifacts_dir / "run_id.txt").write_text(run_id, encoding="utf-8")
        logger.update_artifacts_path(run_id, run_artifacts_dir)

    (DATA_DIR / "run_id.txt").write_text(run_id, encoding="utf-8")

    print("✅ Training finished. Final loss:", f"{total_loss.item():.6e}")
    print(f"Run ID: {run_id}")
    print(f"Artifacts saved to: {run_artifacts_dir.resolve()}")

# ------------------------------------------------------------------------------
# 4️⃣ Script execution guard
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    # Pass through the real command line (skip the script name)
    main(sys.argv[1:])